import FavoritesItem from '@/components/ui/favotites-item/FavoritesItem'
import { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'I comission | Избранное',
	description: 'Generated by create next app'
}
export default function FavoritesPage() {
	return (
		<div>
			<h1>Hi</h1>
			{/* <FavoritesItem /> */}
		</div>
	)
}
